public  class ArthimaticCalculation {

    public void Addition(integer x, integer y){
        integer z = x+y;
        system.debug('The result of addition: ' + z);
    }

    public void Subtraction (integer x, integer y){
        integer z = x-y;
        system.debug('The result of subtraction: ' + z);
    }


    public void Multiplication (integer x, integer y, integer m){
        integer z = x*y*m;
        system.debug('The result of multiplication: ' + z);
    }

    

   
}