public class CheckDataTypes {
    public void MethodBolean(){
        Boolean checkBoolean = false;
        system.debug('The Boolean is ' + checkBoolean );

    }
    public void MethodInteger(){
        Integer varFirst = 1;
        Integer varSecond = 2;
        system.debug('The first variable ' + varFirst + 'second variable is ' + varSecond);
    }

    public void StringMethod() {
        String varName = 'Name:';
        String var2Name = 'Emine';
        system.debug(varName + ' ' + var2Name);
    }

}
